import fs from "fs";
import path from "path";
import { getSupabase, isSupabaseConfigured } from "./supabase";
import { Category, Product, Article } from "./types";

const DATA_DIR = path.join(process.cwd(), "data");

function readLocalJson<T>(filename: string): T[] {
  try {
    return JSON.parse(fs.readFileSync(path.join(DATA_DIR, filename), "utf-8"));
  } catch {
    return [];
  }
}

// ─── camelCase ↔ snake_case マッパー ──────────────────

function toArticle(row: Record<string, unknown>): Article {
  return {
    id: row.id as string,
    title: row.title as string,
    slug: row.slug as string,
    categoryId: row.category_id as string,
    content: row.content as string,
    excerpt: row.excerpt as string,
    productIds: (row.product_ids as string[]) || [],
    status: row.status as "draft" | "published",
    faqs: (row.faqs as Article["faqs"]) || [],
    metaDescription: (row.meta_description as string) || "",
    tags: (row.tags as string[]) || [],
    createdAt: row.created_at as string,
    updatedAt: row.updated_at as string,
    publishedAt: (row.published_at as string) || null,
    autoGenerated: (row.auto_generated as boolean) || false,
    qualityScore: row.quality_score as number | undefined,
    scheduledPublishDate: row.scheduled_publish_date as string | undefined,
    generationMeta: row.generation_meta as Article["generationMeta"],
    eyecatch: (row.eyecatch as string) || undefined,
  };
}

function fromArticle(article: Article): Record<string, unknown> {
  return {
    id: article.id,
    title: article.title,
    slug: article.slug,
    category_id: article.categoryId,
    content: article.content,
    excerpt: article.excerpt,
    product_ids: article.productIds,
    status: article.status,
    faqs: article.faqs || [],
    meta_description: article.metaDescription || "",
    tags: article.tags || [],
    created_at: article.createdAt,
    updated_at: article.updatedAt,
    published_at: article.publishedAt,
    auto_generated: article.autoGenerated || false,
    quality_score: article.qualityScore ?? null,
    scheduled_publish_date: article.scheduledPublishDate ?? null,
    generation_meta: article.generationMeta ?? null,
    eyecatch: article.eyecatch ?? null,
  };
}

function toCategory(row: Record<string, unknown>): Category {
  return {
    id: row.id as string,
    name: row.name as string,
    slug: row.slug as string,
    description: row.description as string,
    order: row.sort_order as number,
  };
}

function fromCategory(category: Category): Record<string, unknown> {
  return {
    id: category.id,
    name: category.name,
    slug: category.slug,
    description: category.description,
    sort_order: category.order,
  };
}

function toProduct(row: Record<string, unknown>): Product {
  return {
    id: row.id as string,
    name: row.name as string,
    brand: row.brand as string,
    price: row.price as number,
    imageUrl: row.image_url as string,
    affiliateUrl: row.affiliate_url as string,
    amazonUrl: row.amazon_url as string,
    categoryId: row.category_id as string,
    specs: (row.specs as Record<string, string>) || {},
    description: row.description as string,
    rating: row.rating as number,
    createdAt: row.created_at as string,
    updatedAt: row.updated_at as string,
    autoAdded: row.auto_added as boolean | undefined,
    addedBy: row.added_by as string | undefined,
    addedAt: row.added_at as string | undefined,
    sourceApi: row.source_api as string | undefined,
    availability: (row.availability as "InStock" | "OutOfStock" | "Unknown") ?? undefined,
  };
}

function fromProduct(product: Product): Record<string, unknown> {
  return {
    id: product.id,
    name: product.name,
    brand: product.brand,
    price: product.price,
    image_url: product.imageUrl,
    affiliate_url: product.affiliateUrl,
    amazon_url: product.amazonUrl,
    category_id: product.categoryId,
    specs: product.specs,
    description: product.description,
    rating: product.rating,
    created_at: product.createdAt,
    updated_at: product.updatedAt,
    auto_added: product.autoAdded ?? null,
    added_by: product.addedBy ?? null,
    added_at: product.addedAt ?? null,
    source_api: product.sourceApi ?? null,
    availability: product.availability ?? null,
  };
}

// ─── Categories ─────────────────────────────────────

export async function getCategories(): Promise<Category[]> {
  const localCats = readLocalJson<Category>("categories.json");
  const sceneCats = localCats.filter((c) => c.type === "scene");

  if (!isSupabaseConfigured()) {
    return localCats.slice().sort((a, b) => a.order - b.order);
  }
  const { data, error } = await getSupabase()
    .from("categories")
    .select("*")
    .order("sort_order", { ascending: true });
  if (error) throw error;
  const supaCats = (data || []).map(toCategory);
  // シーン別カテゴリはローカルJSONから、通常カテゴリはSupabaseから
  return [...sceneCats, ...supaCats].sort((a, b) => a.order - b.order);
}

export async function getCategoryBySlug(
  slug: string
): Promise<Category | undefined> {
  if (!isSupabaseConfigured()) {
    return readLocalJson<Category>("categories.json").find((c) => c.slug === slug);
  }
  const { data, error } = await getSupabase()
    .from("categories")
    .select("*")
    .eq("slug", slug)
    .maybeSingle();
  if (error) throw error;
  return data ? toCategory(data) : undefined;
}

export async function getCategoryById(
  id: string
): Promise<Category | undefined> {
  if (!isSupabaseConfigured()) {
    return readLocalJson<Category>("categories.json").find((c) => c.id === id);
  }
  const { data, error } = await getSupabase()
    .from("categories")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  return data ? toCategory(data) : undefined;
}

export async function saveCategory(category: Category): Promise<void> {
  const { error } = await getSupabase()
    .from("categories")
    .upsert(fromCategory(category), { onConflict: "id" });
  if (error) throw error;
}

export async function deleteCategory(id: string): Promise<void> {
  const { error } = await getSupabase().from("categories").delete().eq("id", id);
  if (error) throw error;
}

// ─── Products ───────────────────────────────────────

export async function getProducts(): Promise<Product[]> {
  if (!isSupabaseConfigured()) return readLocalJson<Product>("products.json");
  const { data, error } = await getSupabase()
    .from("products")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) throw error;
  return (data || []).map(toProduct);
}

export async function getProductById(
  id: string
): Promise<Product | undefined> {
  const { data, error } = await getSupabase()
    .from("products")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  return data ? toProduct(data) : undefined;
}

export async function getProductsByCategory(
  categoryId: string
): Promise<Product[]> {
  const { data, error } = await getSupabase()
    .from("products")
    .select("*")
    .eq("category_id", categoryId);
  if (error) throw error;
  return (data || []).map(toProduct);
}

export async function getProductsByIds(ids: string[]): Promise<Product[]> {
  if (ids.length === 0) return [];
  if (!isSupabaseConfigured()) {
    const all = readLocalJson<Product>("products.json");
    return ids
      .map((id) => all.find((p) => p.id === id))
      .filter((p): p is Product => p !== undefined);
  }
  const { data, error } = await getSupabase()
    .from("products")
    .select("*")
    .in("id", ids);
  if (error) throw error;
  // 入力IDの順序を保持（ランキング順）
  const mapped = (data || []).map(toProduct);
  return ids
    .map((id) => mapped.find((p) => p.id === id))
    .filter((p): p is Product => p !== undefined);
}

export async function saveProduct(product: Product): Promise<void> {
  const { error } = await getSupabase()
    .from("products")
    .upsert(fromProduct(product), { onConflict: "id" });
  if (error) throw error;
}

export async function deleteProduct(id: string): Promise<void> {
  const { error } = await getSupabase().from("products").delete().eq("id", id);
  if (error) throw error;
}

// ─── Articles ───────────────────────────────────────

export async function getArticles(): Promise<Article[]> {
  if (!isSupabaseConfigured()) return readLocalJson<Article>("articles.json");
  const { data, error } = await getSupabase()
    .from("articles")
    .select("*")
    .order("updated_at", { ascending: false });
  if (error) throw error;
  return (data || []).map(toArticle);
}

// ─── 一覧用の軽量取得（本文を転送しない = Egress削減） ────────
// 一覧・sitemap・feed・llms・トップ・カテゴリは content/faqs/generation_meta を
// 使わないため、巨大な content 列を除いて取得する。1記事最大32KBの content を
// 100本超×クローラー多数のアクセスで毎回引くのがEgress肥大の主因だった。
const ARTICLE_LIST_COLS =
  "id, title, slug, category_id, excerpt, product_ids, status, meta_description, tags, created_at, updated_at, published_at, auto_generated, quality_score, scheduled_publish_date, eyecatch";

function toArticleListItem(row: Record<string, unknown>): Article {
  // content/faqs/generation_meta は一覧では未取得 → 空で埋める（型互換のため）
  return toArticle({ ...row, content: "", faqs: [], generation_meta: null });
}

export async function getPublishedArticles(): Promise<Article[]> {
  if (!isSupabaseConfigured()) {
    return readLocalJson<Article>("articles.json").filter(
      (a) => a.status === "published"
    );
  }
  const { data, error } = await getSupabase()
    .from("articles")
    .select("*")
    .eq("status", "published")
    .order("updated_at", { ascending: false });
  if (error) throw error;
  return (data || []).map(toArticle);
}

// 一覧表示・sitemap・feed・llms 用。本文を含まない軽量版。
export async function getPublishedArticlesList(): Promise<Article[]> {
  if (!isSupabaseConfigured()) {
    return readLocalJson<Article>("articles.json").filter(
      (a) => a.status === "published"
    );
  }
  const { data, error } = await getSupabase()
    .from("articles")
    .select(ARTICLE_LIST_COLS)
    .eq("status", "published")
    .order("updated_at", { ascending: false });
  if (error) throw error;
  return (data || []).map(toArticleListItem);
}

// sitemap 用（下書き含む全記事の軽量メタ。sitemapは公開のみ使うが将来用に全件）
export async function getArticlesList(): Promise<Article[]> {
  if (!isSupabaseConfigured()) return readLocalJson<Article>("articles.json");
  const { data, error } = await getSupabase()
    .from("articles")
    .select(ARTICLE_LIST_COLS)
    .order("updated_at", { ascending: false });
  if (error) throw error;
  return (data || []).map(toArticleListItem);
}

export async function getArticleBySlug(
  slug: string
): Promise<Article | undefined> {
  if (!isSupabaseConfigured()) {
    return readLocalJson<Article>("articles.json").find((a) => a.slug === slug);
  }
  const { data, error } = await getSupabase()
    .from("articles")
    .select("*")
    .eq("slug", slug)
    .maybeSingle();
  if (error) throw error;
  return data ? toArticle(data) : undefined;
}

export async function getArticleById(
  id: string
): Promise<Article | undefined> {
  if (!isSupabaseConfigured()) {
    return readLocalJson<Article>("articles.json").find((a) => a.id === id);
  }
  const { data, error } = await getSupabase()
    .from("articles")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  return data ? toArticle(data) : undefined;
}

export async function getArticlesByCategory(
  categoryId: string
): Promise<Article[]> {
  // シーン別カテゴリはarticleSlugで記事を特定
  const localCats = readLocalJson<Category>("categories.json");
  const sceneCategory = localCats.find(
    (c) => (c.slug === categoryId || c.id === categoryId) && c.type === "scene"
  );

  if (sceneCategory?.articleSlugs?.length) {
    const slugs = sceneCategory.articleSlugs;
    if (!isSupabaseConfigured()) {
      const all = readLocalJson<Article>("articles.json");
      return slugs
        .map((s) => all.find((a) => a.slug === s && a.status === "published"))
        .filter((a): a is Article => a !== undefined);
    }
    const { data, error } = await getSupabase()
      .from("articles")
      .select(ARTICLE_LIST_COLS) // カテゴリ一覧は本文不使用 → 軽量取得
      .eq("status", "published")
      .in("slug", slugs);
    if (error) throw error;
    const mapped = (data || []).map(toArticleListItem);
    return slugs
      .map((s) => mapped.find((a) => a.slug === s))
      .filter((a): a is Article => a !== undefined);
  }

  // 通常カテゴリ
  if (!isSupabaseConfigured()) {
    return readLocalJson<Article>("articles.json").filter(
      (a) => a.status === "published" && a.categoryId === categoryId
    );
  }
  const { data, error } = await getSupabase()
    .from("articles")
    .select(ARTICLE_LIST_COLS) // カテゴリ一覧は本文不使用 → 軽量取得
    .eq("status", "published")
    .eq("category_id", categoryId)
    .order("updated_at", { ascending: false });
  if (error) throw error;
  return (data || []).map(toArticleListItem);
}

export async function saveArticle(article: Article): Promise<void> {
  const { error } = await getSupabase()
    .from("articles")
    .upsert(fromArticle(article), { onConflict: "id" });
  if (error) throw error;
}

export async function deleteArticle(id: string): Promise<void> {
  const { error } = await getSupabase().from("articles").delete().eq("id", id);
  if (error) throw error;
}
