export interface Category {
  id: string;
  name: string;
  slug: string;
  description: string;
  order: number;
  type?: "scene" | "product";
  articleSlugs?: string[];
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  imageUrl: string;
  affiliateUrl: string;
  amazonUrl: string;
  categoryId: string;
  specs: Record<string, string>;
  description: string;
  rating: number; // 1-5
  createdAt: string;
  updatedAt: string;
  // --- 記事パイプライン自動追加 ---
  autoAdded?: boolean;
  addedBy?: string;
  addedAt?: string;
  sourceApi?: string;
  availability?: "InStock" | "OutOfStock" | "Unknown";
}

export interface FAQ {
  question: string;
  answer: string;
}

export type XPostType =
  | "article_promo"
  | "outdoor_tip"
  | "article_repost"
  | "seasonal"
  | "rakuten_sale"
  | "amazon_deal"
  | "news_comment"
  | "rakuten_room_pick"
  | "gear_story"
  | "poll_question"
  | "failure_story"
  | "gear_thread"
  | "ai_dev_log"
  | "parenting_outdoor"
  | "doc_health_tip"
  | "seasonal_hook"
  | "repost_rewrite";

export type XPostStatus = "draft" | "approved" | "queued" | "posted" | "discarded";

export type XPostSlot = "morning" | "noon" | "night";

export interface XPost {
  id: string;
  type: XPostType;
  text: string;
  articleSlug: string | null;
  url: string | null;
  hashtags: string;
  status: XPostStatus;
  scheduledDate: string;
  generatedAt: string;
  postedAt: string | null;
  // --- K〜N列: generate-x-posts.js が書き込む実カラムに準拠 ---
  /** 発信4軸 (camp/ai/parenting/doctor) */
  axis?: string;
  /** 使用したシードID (seed-XXX) */
  seedId?: string;
  /** NGワード/誇大表現チェッカーが返した検出メッセージ */
  validationErrors?: string;
  /** 自動承認フラグ ("true"/"false") */
  autoApproved?: string;
  // --- O〜R列: エージェント化拡張 ---
  /** 自己採点スコア (0.0〜10.0) */
  selfScore?: number;
  /** 書き出しパターン分類 (15カテゴリ) */
  firstLinePattern?: string;
  /** 直近100件との最大類似度スコア */
  similarityScore?: number;
  /** リトライ回数 (0/1/2) */
  retryCount?: number;
  // --- S列: 投稿直後リプライ ---
  /** 投稿直後にリプ欄に追加するコメント（会話誘発用） */
  selfReply?: string;
  // --- T列: 投稿フォーマットパターン ---
  /** 使用した投稿フォーマットパターンID */
  formatPattern?: string;
  // --- U列: 添付画像URL ---
  /** 投稿に添付する画像URL (Vercel Blob URL or Unsplash or OG image) */
  imageUrl?: string;
}

export interface Article {
  id: string;
  title: string;
  slug: string;
  categoryId: string;
  content: string; // Markdown
  excerpt: string;
  productIds: string[];
  status: "draft" | "published";
  faqs?: FAQ[];
  metaDescription?: string;
  tags?: string[];
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
  // --- 自動生成パイプライン拡張 ---
  autoGenerated?: boolean;
  qualityScore?: number;
  scheduledPublishDate?: string;
  generationMeta?: {
    themeId: string;
    model: string;
    retryCount: number;
    generatedAt: string;
  };
}
