import { getArticles, getProducts, getCategories } from "@/lib/db";
import { getSupabase } from "@/lib/supabase";
import Link from "next/link";

export const dynamic = "force-dynamic";

async function getClickStats() {
  try {
    const supabase = getSupabase();
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
    const { data, error } = await supabase
      .from("affiliate_clicks")
      .select("product_id, store, clicked_at")
      .gte("clicked_at", sevenDaysAgo);
    if (error || !data) return { total: 0, byStore: {} as Record<string, number>, topProducts: [] as { id: string; count: number }[] };

    const byStore: Record<string, number> = {};
    const byProduct: Record<string, number> = {};
    for (const row of data) {
      byStore[row.store] = (byStore[row.store] || 0) + 1;
      byProduct[row.product_id] = (byProduct[row.product_id] || 0) + 1;
    }
    const topProducts = Object.entries(byProduct)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([id, count]) => ({ id, count }));

    return { total: data.length, byStore, topProducts };
  } catch {
    return { total: 0, byStore: {} as Record<string, number>, topProducts: [] as { id: string; count: number }[] };
  }
}

export default async function AdminDashboard() {
  const [articles, products, categories, clickStats] = await Promise.all([
    getArticles(),
    getProducts(),
    getCategories(),
    getClickStats(),
  ]);

  const published = articles.filter((a) => a.status === "published");
  const drafts = articles.filter((a) => a.status === "draft");
  const today = new Date().toISOString().slice(0, 10);
  const scheduledToday = drafts.filter(
    (a) => a.scheduledPublishDate && a.scheduledPublishDate <= today && (a.qualityScore || 0) >= 6.0
  );

  // 品質スコア分布
  const autoGenerated = articles.filter((a) => a.autoGenerated && a.qualityScore);
  const avgScore = autoGenerated.length > 0
    ? autoGenerated.reduce((s, a) => s + (a.qualityScore || 0), 0) / autoGenerated.length
    : 0;
  const lowQuality = autoGenerated.filter((a) => (a.qualityScore || 0) < 6.0);

  // カテゴリ別記事数
  const catArticleCount: Record<string, number> = {};
  published.forEach((a) => { catArticleCount[a.categoryId] = (catArticleCount[a.categoryId] || 0) + 1; });

  // 商品データ品質
  const noAmazon = products.filter((p) => !p.amazonUrl);
  const noImage = products.filter((p) => !p.imageUrl);
  const noAffiliate = products.filter((p) => !p.affiliateUrl && !p.amazonUrl);

  // クリックの多い商品名を解決
  const topClickProducts = clickStats.topProducts.map((tp) => {
    const prod = products.find((p) => p.id === tp.id);
    return { name: prod?.name || tp.id, count: tp.count };
  });

  const stats = [
    { label: "公開記事", value: published.length, color: "bg-emerald-500", href: "/admin/articles" },
    { label: "下書き", value: drafts.length, color: "bg-amber-500", href: "/admin/articles" },
    { label: "商品", value: products.length, color: "bg-blue-500", href: "/admin/products" },
    { label: "カテゴリ", value: categories.length, color: "bg-violet-500", href: "/admin/categories" },
  ];

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-800 mb-6">ダッシュボード</h1>

      {/* 基本統計 */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {stats.map((stat) => (
          <Link
            key={stat.label}
            href={stat.href}
            className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 hover:shadow-md transition"
          >
            <div className={`w-2.5 h-2.5 rounded-full ${stat.color} mb-2`} />
            <p className="text-3xl font-bold text-gray-800">{stat.value}</p>
            <p className="text-xs text-gray-500 mt-1">{stat.label}</p>
          </Link>
        ))}
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
        {/* 本日の公開予定 */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">本日の公開予定</h2>
          {scheduledToday.length === 0 ? (
            <p className="text-gray-400 text-sm">なし</p>
          ) : (
            <ul className="space-y-2">
              {scheduledToday.map((a) => (
                <li key={a.id} className="text-sm">
                  <span className="text-gray-700">{a.title}</span>
                  <span className="ml-2 text-xs text-gray-400">スコア {a.qualityScore?.toFixed(1)}</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* 品質スコア */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">記事品質</h2>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-gray-600">平均スコア</span>
              <span className={`font-bold ${avgScore >= 7 ? "text-emerald-600" : avgScore >= 6 ? "text-amber-600" : "text-red-600"}`}>
                {avgScore.toFixed(1)}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-600">自動生成記事</span>
              <span className="text-gray-800">{autoGenerated.length}本</span>
            </div>
            {lowQuality.length > 0 && (
              <div className="flex justify-between text-red-600">
                <span>低品質（6.0未満）</span>
                <span className="font-bold">{lowQuality.length}本</span>
              </div>
            )}
          </div>
        </div>

        {/* アフィリエイトクリック（7日間） */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">クリック数（7日間）</h2>
          {clickStats.total === 0 ? (
            <p className="text-gray-400 text-sm">データなし</p>
          ) : (
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-gray-600">合計</span>
                <span className="font-bold text-blue-600">{clickStats.total}</span>
              </div>
              {Object.entries(clickStats.byStore).map(([store, count]) => (
                <div key={store} className="flex justify-between">
                  <span className="text-gray-600">{store}</span>
                  <span className="text-gray-800">{count}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-4 mb-6">
        {/* カテゴリ別記事数 */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">カテゴリ別記事数</h2>
          <div className="space-y-1.5">
            {categories
              .map((c) => ({ ...c, count: catArticleCount[c.id] || 0 }))
              .sort((a, b) => b.count - a.count)
              .map((c) => (
                <div key={c.id} className="flex items-center gap-2 text-sm">
                  <div className="flex-1">
                    <div className="flex justify-between mb-0.5">
                      <span className="text-gray-700">{c.name}</span>
                      <span className={`font-medium ${c.count <= 1 ? "text-red-500" : "text-gray-800"}`}>
                        {c.count}
                      </span>
                    </div>
                    <div className="w-full bg-gray-100 rounded-full h-1.5">
                      <div
                        className={`h-1.5 rounded-full ${c.count <= 1 ? "bg-red-400" : c.count <= 2 ? "bg-amber-400" : "bg-emerald-400"}`}
                        style={{ width: `${Math.min((c.count / 11) * 100, 100)}%` }}
                      />
                    </div>
                  </div>
                </div>
              ))}
          </div>
        </div>

        {/* 商品データ品質 + クリックTop5 */}
        <div className="space-y-4">
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
            <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">商品データ品質</h2>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-gray-600">総商品数</span>
                <span className="text-gray-800">{products.length}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Amazon URL なし</span>
                <span className={noAmazon.length > 0 ? "text-amber-600 font-medium" : "text-emerald-600"}>
                  {noAmazon.length}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">画像なし</span>
                <span className={noImage.length > 0 ? "text-red-600 font-medium" : "text-emerald-600"}>
                  {noImage.length}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">リンクなし（楽天+Amazon両方）</span>
                <span className={noAffiliate.length > 0 ? "text-red-600 font-medium" : "text-emerald-600"}>
                  {noAffiliate.length}
                </span>
              </div>
            </div>
          </div>

          {topClickProducts.length > 0 && (
            <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
              <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">クリック Top 5</h2>
              <ol className="space-y-1.5 text-sm">
                {topClickProducts.map((p, i) => (
                  <li key={i} className="flex justify-between">
                    <span className="text-gray-700 truncate mr-2">{i + 1}. {p.name}</span>
                    <span className="text-blue-600 font-medium shrink-0">{p.count}</span>
                  </li>
                ))}
              </ol>
            </div>
          )}
        </div>
      </div>

      {/* 最近の記事 + クイックアクション */}
      <div className="grid md:grid-cols-2 gap-4">
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">最近の記事</h2>
          <ul className="space-y-2">
            {articles.slice(0, 8).map((a) => (
              <li key={a.id} className="flex items-center justify-between gap-2">
                <Link
                  href={`/admin/articles?edit=${a.id}`}
                  className="text-sm text-gray-700 hover:text-blue-600 truncate"
                >
                  {a.title}
                </Link>
                <span
                  className={`text-xs px-2 py-0.5 rounded-full shrink-0 ${
                    a.status === "published"
                      ? "bg-emerald-50 text-emerald-700"
                      : "bg-amber-50 text-amber-700"
                  }`}
                >
                  {a.status === "published" ? "公開" : "下書き"}
                </span>
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">クイックアクション</h2>
          <div className="space-y-2">
            <Link
              href="/admin/articles?new=1"
              className="block w-full text-center bg-emerald-600 text-white py-2.5 rounded-lg hover:bg-emerald-700 transition text-sm font-medium"
            >
              + 新しい記事を作成
            </Link>
            <Link
              href="/admin/products?new=1"
              className="block w-full text-center bg-blue-600 text-white py-2.5 rounded-lg hover:bg-blue-700 transition text-sm font-medium"
            >
              + 新しい商品を登録
            </Link>
            <Link
              href="/admin/x-posts"
              className="block w-full text-center bg-gray-800 text-white py-2.5 rounded-lg hover:bg-gray-900 transition text-sm font-medium"
            >
              X 投稿管理
            </Link>
            <a
              href="https://camp-gear-lab.com"
              target="_blank"
              rel="noopener noreferrer"
              className="block w-full text-center border border-gray-200 text-gray-600 py-2.5 rounded-lg hover:bg-gray-50 transition text-sm"
            >
              サイトを表示 →
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
